apiVersion: v1
kind: Pod
metadata:
  name: main-app
spec:
     containers:
     - command: ["/bin/bash"]
       args: ["-c", "cp -f ./docker_config_prod/*.cfg /usr/src/app/example_reporting_main/config/. ; python example_reporting_main/main.py"]
       image: sarramagna/example_reporting_main
       name: main-app
       ports:
       - containerPort: 50603
       env:
       - name: email_sender
         valueFrom:
           secretKeyRef:
             name: main-secret
             key: EMAIL_SENDER
       - name: email_receiver
         valueFrom:
           secretKeyRef:
             name: main-secret
             key: EMAIL_RECEIVER
       - name: secure_mode_login
         valueFrom:
           secretKeyRef:
             name: main-secret
             key: SECURE_MODE_LOGIN
       - name: secure_mode_pwd
         valueFrom:
           secretKeyRef:
             name: main-secret
             key: SECURE_MODE_PWD
     restartPolicy: Never

       

